"""changed expense model

Revision ID: 70b4eb842cc3
Revises: 2296126f441f
Create Date: 2025-03-09 15:33:55.792332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b4eb842cc3'
down_revision: Union[str, None] = '2296126f441f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('expense_category', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('expense_name', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('expense_amount', sa.String(), nullable=True))
    op.drop_column('expenses', 'expense_type')
    op.drop_column('expenses', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('amount', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('expense_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('expenses', 'expense_amount')
    op.drop_column('expenses', 'expense_name')
    op.drop_column('expenses', 'expense_category')
    # ### end Alembic commands ###
