"""updated expense amount from string to float  id to category  model

Revision ID: 7d0d05ed09ae
Revises: ac9dffbb2b9d
Create Date: 2025-05-28 22:20:27.712319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0d05ed09ae'
down_revision: Union[str, None] = 'ac9dffbb2b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'expense_amount',
               existing_type=sa.VARCHAR(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'expense_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
