"""added default curreny field to user

Revision ID: bd4ebd01f6c8
Revises: dd5987f0005f
Create Date: 2025-03-23 13:19:20.785235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4ebd01f6c8'
down_revision: Union[str, None] = 'dd5987f0005f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    # ### end Alembic commands ###
