"""added new field to model

Revision ID: c7802134d87b
Revises: f6351314f365
Create Date: 2025-05-24 17:48:33.419565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7802134d87b'
down_revision: Union[str, None] = 'f6351314f365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('insertion_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'insertion_type')
    # ### end Alembic commands ###
